spring.application.name=videorent
spring.datasource.url=jdbc:postgresql://localhost:5432/videorent
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.upload.dir=uploads/images
spring.web.resources.static-locations=classpath:/static/,file:uploads/
